export const books = [
  {
    id: 1,
    title: "ملت عشق",
    author: "الیف شافاک",
    price: 180000,
    categoryId: 1,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 2,
    title: "انسان در جستجوی معنا",
    author: "ویکتور فرانکل",
    price: 145000,
    categoryId: 2,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 3,
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 320000,
    categoryId: 4,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 4,
    title: "اثر مرکب",
    author: "دارن هاردی",
    price: 160000,
    categoryId: 3,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 5,
    title: "شازده احتجاب",
    author: "هوشنگ گلشیری",
    price: 180000,
    categoryId: 1,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 6,
    title: "کلیسای جامع",
    author: "ریموند کارور",
    price: 145000,
    categoryId: 2,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 7,
    title: "Programming in C",
    author: "Stephen Prata",
    price: 320000,
    categoryId: 4,
    image: "https://placehold.co/300x400?text=Book",
  },
  {
    id: 8,
    title: "کی گفته",
    author: "دارن همیلتون",
    price: 160000,
    categoryId: 8,
    image: "https://placehold.co/300x400?text=Book",
  },
];
